
package wstest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Información sobre morosidad de un cliente
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Servicio_x0020_Web_x0020_Sistema_x0020_Comercial", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", wsdlLocation = "https://servicios.electricaribe.com/wssistemacomercial/SistemaComercialServicios.asmx?wsdl")
public class ServicioX0020WebX0020SistemaX0020Comercial
    extends Service
{

    private final static URL SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_WSDL_LOCATION;
    private final static WebServiceException SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_EXCEPTION;
    private final static QName SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_QNAME = new QName("https://webservices.electricaribe.com/ws_sicomercial/", "Servicio_x0020_Web_x0020_Sistema_x0020_Comercial");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://servicios.electricaribe.com/wssistemacomercial/SistemaComercialServicios.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_WSDL_LOCATION = url;
        SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_EXCEPTION = e;
    }

    public ServicioX0020WebX0020SistemaX0020Comercial() {
        super(__getWsdlLocation(), SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_QNAME);
    }

    public ServicioX0020WebX0020SistemaX0020Comercial(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_QNAME, features);
    }

    public ServicioX0020WebX0020SistemaX0020Comercial(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_QNAME);
    }

    public ServicioX0020WebX0020SistemaX0020Comercial(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_QNAME, features);
    }

    public ServicioX0020WebX0020SistemaX0020Comercial(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioX0020WebX0020SistemaX0020Comercial(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioX0020WebX0020SistemaX0020ComercialSoap
     */
    @WebEndpoint(name = "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap")
    public ServicioX0020WebX0020SistemaX0020ComercialSoap getServicioX0020WebX0020SistemaX0020ComercialSoap() {
        return super.getPort(new QName("https://webservices.electricaribe.com/ws_sicomercial/", "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap"), ServicioX0020WebX0020SistemaX0020ComercialSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioX0020WebX0020SistemaX0020ComercialSoap
     */
    @WebEndpoint(name = "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap")
    public ServicioX0020WebX0020SistemaX0020ComercialSoap getServicioX0020WebX0020SistemaX0020ComercialSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.electricaribe.com/ws_sicomercial/", "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap"), ServicioX0020WebX0020SistemaX0020ComercialSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ServicioX0020WebX0020SistemaX0020ComercialSoap
     */
    @WebEndpoint(name = "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap12")
    public ServicioX0020WebX0020SistemaX0020ComercialSoap getServicioX0020WebX0020SistemaX0020ComercialSoap12() {
        return super.getPort(new QName("https://webservices.electricaribe.com/ws_sicomercial/", "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap12"), ServicioX0020WebX0020SistemaX0020ComercialSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioX0020WebX0020SistemaX0020ComercialSoap
     */
    @WebEndpoint(name = "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap12")
    public ServicioX0020WebX0020SistemaX0020ComercialSoap getServicioX0020WebX0020SistemaX0020ComercialSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://webservices.electricaribe.com/ws_sicomercial/", "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap12"), ServicioX0020WebX0020SistemaX0020ComercialSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_EXCEPTION!= null) {
            throw SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_EXCEPTION;
        }
        return SERVICIOX0020WEBX0020SISTEMAX0020COMERCIAL_WSDL_LOCATION;
    }

}
