
package wstest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Servicio_x0020_Web_x0020_Sistema_x0020_ComercialSoap", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioX0020WebX0020SistemaX0020ComercialSoap {


    /**
     * 
     * @param nic
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EsClienteMoroso", action = "https://webservices.electricaribe.com/ws_sicomercial/EsClienteMoroso")
    @WebResult(name = "EsClienteMorosoResult", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
    @RequestWrapper(localName = "EsClienteMoroso", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.EsClienteMoroso")
    @ResponseWrapper(localName = "EsClienteMorosoResponse", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.EsClienteMorosoResponse")
    public String esClienteMoroso(
        @WebParam(name = "nic", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
        long nic);

    /**
     * 
     * @param nics
     * @return
     *     returns wstest.ArrayOfString
     */
    @WebMethod(operationName = "EsClienteMorosoMasivo", action = "https://webservices.electricaribe.com/ws_sicomercial/EsClienteMorosoMasivo")
    @WebResult(name = "EsClienteMorosoMasivoResult", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
    @RequestWrapper(localName = "EsClienteMorosoMasivo", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.EsClienteMorosoMasivo")
    @ResponseWrapper(localName = "EsClienteMorosoMasivoResponse", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.EsClienteMorosoMasivoResponse")
    public ArrayOfString esClienteMorosoMasivo(
        @WebParam(name = "nics", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
        ArrayOfLong nics);

    /**
     * 
     * @param nic
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaIdCobro", action = "https://webservices.electricaribe.com/ws_sicomercial/ConsultaIdCobro")
    @WebResult(name = "ConsultaIdCobroResult", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
    @RequestWrapper(localName = "ConsultaIdCobro", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.ConsultaIdCobro")
    @ResponseWrapper(localName = "ConsultaIdCobroResponse", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.ConsultaIdCobroResponse")
    public String consultaIdCobro(
        @WebParam(name = "nic", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
        long nic);

    /**
     * 
     * @param nic
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValorFacturaActual", action = "https://webservices.electricaribe.com/ws_sicomercial/ValorFacturaActual")
    @WebResult(name = "ValorFacturaActualResult", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
    @RequestWrapper(localName = "ValorFacturaActual", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.ValorFacturaActual")
    @ResponseWrapper(localName = "ValorFacturaActualResponse", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.ValorFacturaActualResponse")
    public String valorFacturaActual(
        @WebParam(name = "nic", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
        long nic);

    /**
     * 
     * @param sarta
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AsociarOrdenesServicio", action = "https://webservices.electricaribe.com/ws_sicomercial/AsociarOrdenesServicio")
    @WebResult(name = "AsociarOrdenesServicioResult", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
    @RequestWrapper(localName = "AsociarOrdenesServicio", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.AsociarOrdenesServicio")
    @ResponseWrapper(localName = "AsociarOrdenesServicioResponse", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/", className = "wstest.AsociarOrdenesServicioResponse")
    public String asociarOrdenesServicio(
        @WebParam(name = "sarta", targetNamespace = "https://webservices.electricaribe.com/ws_sicomercial/")
        String sarta);

}
